name: Publish Saya release
on:
  schedule:
    - cron: '30 0 30 8 *'
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release edit test-release --repo DivanDoge/locus-team --draft=false